//! Generate Python dataclass definitions, error IntEnums, and the top-level `generate_python()`.

use crate::ast::{LaicFile, SkillDef};
use crate::codegen::python_deserialize::generate_from_ipc;
use crate::codegen::python_serialize::generate_to_ipc;
use crate::codegen::python_string_literal;
use crate::codegen::python_types::python_type;
use crate::codegen::to_pascal_case;

/// Generate complete Python source code for a parsed and validated `.laic` file.
pub fn generate_python(file: &LaicFile) -> String {
    let mut out = String::with_capacity(4096);

    // Header
    out.push_str("# Generated by laicc — DO NOT EDIT.\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import dataclasses\n");
    out.push_str("import enum\n");
    out.push_str("from typing import ClassVar\n\n");
    out.push_str("import pyarrow as pa\n");
    out.push_str("import pyarrow.ipc as ipc\n\n");

    for skill in &file.skills {
        generate_dataclass(&mut out, skill, &skill.input, "input", &file.version);
        out.push('\n');
        generate_dataclass(&mut out, skill, &skill.output, "output", &file.version);
        out.push('\n');
        if !skill.errors.is_empty() {
            generate_error_enum(&mut out, skill);
            out.push('\n');
        }
    }

    out
}

fn generate_dataclass(
    out: &mut String,
    skill: &SkillDef,
    def: &crate::ast::StructDef,
    direction: &str,
    version: &str,
) {
    out.push_str("@dataclasses.dataclass\n");
    out.push_str(&format!("class {}:\n", def.name));
    out.push_str(&format!(
        "    \"\"\"LAIC contract: skill={}, direction='{direction}'.\"\"\"\n\n",
        python_string_literal(&skill.id)
    ));

    // Class variables
    out.push_str(&format!(
        "    SKILL_ID: ClassVar[str] = {}\n",
        python_string_literal(&skill.id)
    ));
    out.push_str(&format!(
        "    VERSION: ClassVar[str] = {}\n",
        python_string_literal(version)
    ));
    out.push_str(&format!(
        "    DIRECTION: ClassVar[str] = \"{direction}\"\n\n"
    ));

    // Fields — fields with defaults must come after fields without defaults
    let (no_default, has_default): (Vec<_>, Vec<_>) =
        def.fields.iter().partition(|f| f.default.is_none());

    for field in &no_default {
        out.push_str(&format!("    {}: {}\n", field.name, python_type(&field.ty)));
    }
    for field in &has_default {
        if let Some(lit) = &field.default {
            let default_val = crate::codegen::python_types::literal_to_python(lit);
            out.push_str(&format!(
                "    {}: {} = {}\n",
                field.name,
                python_type(&field.ty),
                default_val
            ));
        }
    }
    out.push('\n');

    // to_ipc
    generate_to_ipc(out, skill, def, direction, version);

    // from_ipc
    generate_from_ipc(out, def, &skill.id, version, direction);
}

fn generate_error_enum(out: &mut String, skill: &SkillDef) {
    let enum_name = format!("{}Error", to_pascal_case(&skill.name));

    out.push_str(&format!("class {enum_name}(enum.IntEnum):\n"));
    out.push_str(&format!(
        "    \"\"\"Error codes for skill {}.\"\"\"\n\n",
        python_string_literal(&skill.id)
    ));
    for variant in &skill.errors {
        out.push_str(&format!("    {} = {}\n", variant.name, variant.code));
    }
    out.push('\n');
}
