//! Generate Rust struct definitions, error enums, and the top-level `generate_rust()` entry point.

use crate::ast::{LaicFile, SkillDef};
use crate::codegen::rust_deserialize::generate_from_arrow_ipc;
use crate::codegen::rust_serialize::generate_to_arrow_ipc;
use crate::codegen::rust_string_literal;
use crate::codegen::rust_types::rust_type;
use crate::codegen::to_pascal_case;
use crate::error::CompileError;

/// Generate complete Rust source code for a parsed and validated `.laic` file.
///
/// # Errors
///
/// Returns `CompileError::Codegen` if code generation fails.
pub fn generate_rust(file: &LaicFile) -> Result<String, CompileError> {
    let mut out = String::with_capacity(4096);

    // Header
    out.push_str("// Generated by laicc — DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str("// Dependencies required in your Cargo.toml:\n");
    out.push_str("//   arrow-array, arrow-schema, arrow-ipc\n\n");

    out.push_str("use arrow_array::*;\n");
    out.push_str("use arrow_array::builder::*;\n");
    out.push_str("use arrow_schema::*;\n");
    out.push_str("use std::collections::HashMap;\n");
    out.push_str("use std::sync::Arc;\n\n");

    for skill in &file.skills {
        generate_struct(&mut out, skill, &skill.input, "input", &file.version);
        out.push('\n');
        generate_struct(&mut out, skill, &skill.output, "output", &file.version);
        out.push('\n');
        if !skill.errors.is_empty() {
            generate_error_enum(&mut out, skill);
            out.push('\n');
        }
    }

    Ok(out)
}

fn generate_struct(
    out: &mut String,
    skill: &SkillDef,
    def: &crate::ast::StructDef,
    direction: &str,
    version: &str,
) {
    // Struct definition
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {} {{\n", def.name));
    for field in &def.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_type(&field.ty)
        ));
    }
    out.push_str("}\n\n");

    // impl block with to_arrow_ipc / from_arrow_ipc
    out.push_str(&format!("impl {} {{\n", def.name));

    // Skill metadata accessors
    out.push_str(&format!(
        "    /// Skill ID for this struct.\n    pub fn skill_id() -> &'static str {{ {} }}\n\n",
        rust_string_literal(&skill.id)
    ));
    out.push_str(&format!(
        "    /// Contract version.\n    pub fn version() -> &'static str {{ {} }}\n\n",
        rust_string_literal(version)
    ));
    out.push_str(&format!(
        "    /// Direction (input or output).\n    pub fn direction() -> &'static str {{ \"{}\" }}\n\n",
        direction
    ));

    generate_to_arrow_ipc(out, skill, def, direction, version);
    out.push('\n');
    generate_from_arrow_ipc(out, def, &skill.id, version, direction);

    out.push_str("}\n");
}

fn generate_error_enum(out: &mut String, skill: &SkillDef) {
    let enum_name = format!("{}Error", to_pascal_case(&skill.name));

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("#[repr(u16)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));
    for variant in &skill.errors {
        out.push_str(&format!(
            "    {} = {},\n",
            to_pascal_case(&variant.name),
            variant.code
        ));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl {enum_name} {{\n"));

    // from_code
    out.push_str("    pub fn from_code(code: u16) -> Option<Self> {\n");
    out.push_str("        match code {\n");
    for variant in &skill.errors {
        out.push_str(&format!(
            "            {} => Some(Self::{}),\n",
            variant.code,
            to_pascal_case(&variant.name)
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // code
    out.push_str("    pub fn code(&self) -> u16 {\n");
    out.push_str("        *self as u16\n");
    out.push_str("    }\n\n");

    // name
    out.push_str("    pub fn name(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for variant in &skill.errors {
        out.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            to_pascal_case(&variant.name),
            variant.name
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");

    out.push_str("}\n");
}
