//! TypeScript contract generation.
//!
//! WHY: Phase 7B deliberately keeps TypeScript output as a single generated file with
//! file-local helpers. This preserves the LAIC mechanism-layer boundary and avoids
//! sliding into a standalone TypeScript SDK/runtime package.

use crate::ast::{LaicFile, SkillDef, StructDef};
use crate::codegen::to_pascal_case;
use crate::codegen::typescript_deserialize::generate_from_ipc;
use crate::codegen::typescript_serialize::generate_to_ipc;
use crate::codegen::typescript_string_literal;
use crate::codegen::typescript_types::{literal_to_ts, ts_type};

/// Generate TypeScript source code from a validated [`LaicFile`].
pub fn generate_typescript(file: &LaicFile) -> String {
    let mut out = String::with_capacity(8192);

    out.push_str("// Generated by laicc - DO NOT EDIT.\n\n");
    out.push_str("import * as arrow from \"apache-arrow\";\n\n");
    append_file_helpers(&mut out);

    for skill in &file.skills {
        generate_class(&mut out, skill, &skill.input, "input", &file.version);
        out.push('\n');
        generate_class(&mut out, skill, &skill.output, "output", &file.version);
        out.push('\n');
        if !skill.errors.is_empty() {
            generate_error_enum(&mut out, skill);
            out.push('\n');
        }
    }

    out
}

fn append_file_helpers(out: &mut String) {
    // Keep guardrails inside the generated file so the artifact remains self-contained:
    // every generated class shares the same metadata validation semantics without an
    // extra helper package.
    out.push_str("function laicSchemaMetadata(schema: any): Map<string, string> {\n");
    out.push_str("  return (schema.metadata ?? new Map()) as Map<string, string>;\n");
    out.push_str("}\n\n");
    out.push_str("function laicFieldMetadata(field: any): Map<string, string> {\n");
    out.push_str("  return (field.metadata ?? new Map()) as Map<string, string>;\n");
    out.push_str("}\n\n");
    out.push_str("function laicAssertMetadata(metadata: Map<string, string>, key: string, expected: string): void {\n");
    out.push_str("  const actual = metadata.get(key);\n");
    out.push_str("  if (actual === undefined) {\n");
    out.push_str("    throw new Error(`missing required metadata key '${key}'`);\n");
    out.push_str("  }\n");
    out.push_str("  if (actual !== expected) {\n");
    out.push_str("    throw new Error(`metadata '${key}' mismatch: expected '${expected}', got '${actual}'`);\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");
    // Tensor shape metadata uses the same compact string representation as the other
    // language targets. Dynamic dimensions stay encoded as `0`, so the parser must
    // preserve that sentinel instead of normalizing it away.
    out.push_str("function laicParseTensorShape(fieldName: string, metadata: Map<string, string>): number[] {\n");
    out.push_str("  const raw = metadata.get(\"laic.tensor.shape\");\n");
    out.push_str("  if (raw === undefined) {\n");
    out.push_str("    throw new Error(`field '${fieldName}': missing tensor shape metadata`);\n");
    out.push_str("  }\n");
    out.push_str("  const body = raw.trim().slice(1, -1).trim();\n");
    out.push_str("  if (body.length === 0) {\n");
    out.push_str("    return [];\n");
    out.push_str("  }\n");
    out.push_str("  return body.split(\",\").map((part) => {\n");
    out.push_str("    const value = Number.parseInt(part.trim(), 10);\n");
    out.push_str("    if (Number.isNaN(value)) {\n");
    out.push_str(
        "      throw new Error(`field '${fieldName}': invalid tensor shape metadata '${raw}'`);\n",
    );
    out.push_str("    }\n");
    out.push_str("    return value;\n");
    out.push_str("  });\n");
    out.push_str("}\n\n");
    // Contract-level tensor checks live here instead of the per-class codegen so all
    // tensor-bearing fields fail with the same semantics across input/output classes.
    out.push_str("function laicAssertTensorMetadata(field: any, fieldName: string, expectedDtype: string, expectedShape: number[]): void {\n");
    out.push_str("  const metadata = laicFieldMetadata(field);\n");
    out.push_str("  laicAssertMetadata(metadata, \"laic.tensor.dtype\", expectedDtype);\n");
    out.push_str("  const actualShape = laicParseTensorShape(fieldName, metadata);\n");
    out.push_str("  if (actualShape.length !== expectedShape.length) {\n");
    out.push_str("    throw new Error(`field '${fieldName}': expected ${expectedShape.length} dimensions, got ${actualShape.length}`);\n");
    out.push_str("  }\n");
    out.push_str("  for (let index = 0; index < expectedShape.length; index += 1) {\n");
    out.push_str("    const expectedDim = expectedShape[index]!;\n");
    out.push_str("    if (expectedDim !== 0 && actualShape[index] !== expectedDim) {\n");
    out.push_str("      throw new Error(`field '${fieldName}': dim ${index} expected ${expectedDim}, got ${actualShape[index]}`);\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");
}

fn generate_class(
    out: &mut String,
    skill: &SkillDef,
    def: &StructDef,
    direction: &str,
    version: &str,
) {
    // Class-centric output is intentional: static metadata, defaults, and IPC methods
    // all stay on one authoritative surface instead of being scattered across helpers.
    out.push_str(&format!("export class {} {{\n", def.name));
    out.push_str(&format!(
        "  static readonly SKILL_ID = {};\n",
        typescript_string_literal(&skill.id)
    ));
    out.push_str(&format!(
        "  static readonly VERSION = {};\n",
        typescript_string_literal(version)
    ));
    out.push_str(&format!(
        "  static readonly DIRECTION = \"{direction}\";\n\n"
    ));

    out.push_str("  constructor(\n");
    for field in &def.fields {
        match &field.default {
            Some(default) => out.push_str(&format!(
                "    public readonly {}: {} = {},\n",
                field.name,
                ts_type(&field.ty),
                literal_to_ts(default)
            )),
            None => out.push_str(&format!(
                "    public readonly {}: {},\n",
                field.name,
                ts_type(&field.ty)
            )),
        }
    }
    out.push_str("  ) {}\n\n");

    generate_to_ipc(out, skill, def, direction, version);
    generate_from_ipc(out, def, &skill.id, version, direction);
    out.push_str("}\n");
}

fn generate_error_enum(out: &mut String, skill: &SkillDef) {
    let enum_name = format!("{}Error", to_pascal_case(&skill.name));
    out.push_str(&format!("export enum {enum_name} {{\n"));
    for variant in &skill.errors {
        out.push_str(&format!("  {} = {},\n", variant.name, variant.code));
    }
    out.push_str("}\n");
}
