//! End-to-end roundtrip tests for laicc-generated code.
//!
//! Each module is generated by `build.rs` from a `.laic` fixture file.
//! The test compiles the generated code against real Arrow APIs and
//! verifies serialize → deserialize roundtrip.

use std::collections::HashMap;

// Include generated modules
// WHY: #[allow(unused)] because verification crate proves code compiles;
// not every generated method is exercised in tests
#[allow(unused)]
mod echo_laic {
    include!(concat!(env!("OUT_DIR"), "/echo_laic.rs"));
}
#[allow(unused)]
mod embedding_laic {
    include!(concat!(env!("OUT_DIR"), "/embedding_laic.rs"));
}
#[allow(unused)]
mod list_types_laic {
    include!(concat!(env!("OUT_DIR"), "/list_types_laic.rs"));
}
#[allow(unused)]
mod map_types_laic {
    include!(concat!(env!("OUT_DIR"), "/map_types_laic.rs"));
}
#[allow(unused)]
mod optional_types_laic {
    include!(concat!(env!("OUT_DIR"), "/optional_types_laic.rs"));
}
#[allow(unused)]
mod tensor_container_laic {
    include!(concat!(env!("OUT_DIR"), "/tensor_container_laic.rs"));
}
#[allow(unused)]
mod image_classify_laic {
    include!(concat!(env!("OUT_DIR"), "/image_classify_laic.rs"));
}
#[allow(unused)]
mod errors_only_laic {
    include!(concat!(env!("OUT_DIR"), "/errors_only_laic.rs"));
}
#[allow(unused)]
mod multi_skill_laic {
    include!(concat!(env!("OUT_DIR"), "/multi_skill_laic.rs"));
}

// Helper: convert a slice of f32 to raw little-endian bytes
fn f32_to_bytes(data: &[f32]) -> Vec<u8> {
    data.iter().flat_map(|v| v.to_le_bytes()).collect()
}

// Helper: convert a slice of f64 to raw little-endian bytes
fn f64_to_bytes(data: &[f64]) -> Vec<u8> {
    data.iter().flat_map(|v| v.to_le_bytes()).collect()
}

// Helper: convert a slice of i32 to raw little-endian bytes
fn i32_to_bytes(data: &[i32]) -> Vec<u8> {
    data.iter().flat_map(|v| v.to_le_bytes()).collect()
}

// ── echo: string → string ──

#[test]
fn echo_roundtrip() {
    let input = echo_laic::EchoInput {
        text: "hello world".into(),
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = echo_laic::EchoInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.text, "hello world");

    let output = echo_laic::EchoOutput {
        text: "echo back".into(),
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = echo_laic::EchoOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.text, "echo back");
}

#[test]
fn echo_metadata() {
    assert_eq!(echo_laic::EchoInput::skill_id(), "echo");
    assert_eq!(echo_laic::EchoInput::version(), "1.0.0");
    assert_eq!(echo_laic::EchoInput::direction(), "input");
    assert_eq!(echo_laic::EchoOutput::direction(), "output");
}

// ── embedding: string + defaults → tensor + i32, errors ──

#[test]
fn embedding_roundtrip() {
    let input = embedding_laic::EmbeddingInput {
        text: "test sentence".into(),
        model: "custom-model".into(),
        max_tokens: 256,
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = embedding_laic::EmbeddingInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.text, "test sentence");
    assert_eq!(decoded.model, "custom-model");
    assert_eq!(decoded.max_tokens, 256);

    // tensor<f32>[768] → Vec<u8> (raw bytes)
    let embedding_f32: Vec<f32> = (0..768).map(|i| i as f32 * 0.001).collect();
    let embedding_bytes = f32_to_bytes(&embedding_f32);
    let output = embedding_laic::EmbeddingOutput {
        embedding: embedding_bytes.clone(),
        token_count: 42,
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = embedding_laic::EmbeddingOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.embedding.len(), 768 * 4); // 768 f32s × 4 bytes
    assert_eq!(decoded.embedding, embedding_bytes);
    assert_eq!(decoded.token_count, 42);
}

#[test]
fn embedding_errors() {
    let e = embedding_laic::EmbeddingError::from_code(1);
    assert!(matches!(
        e,
        Some(embedding_laic::EmbeddingError::InputTooLong)
    ));
    assert_eq!(embedding_laic::EmbeddingError::InputTooLong.code(), 1);
    assert_eq!(
        embedding_laic::EmbeddingError::InputTooLong.name(),
        "INPUT_TOO_LONG"
    );

    assert_eq!(embedding_laic::EmbeddingError::ModelNotFound.code(), 2);
    assert_eq!(embedding_laic::EmbeddingError::InferenceFailed.code(), 3);
    assert!(embedding_laic::EmbeddingError::from_code(999).is_none());
}

// ── list_types: list<string> + list<f32> → list<i32> + bool ──

#[test]
fn list_types_roundtrip() {
    let input = list_types_laic::BatchEmbedInput {
        texts: vec!["hello".into(), "world".into()],
        weights: vec![0.5, 1.0],
        model: "default".into(),
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = list_types_laic::BatchEmbedInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.texts, vec!["hello", "world"]);
    assert_eq!(decoded.weights, vec![0.5f32, 1.0]);
    assert_eq!(decoded.model, "default");

    let output = list_types_laic::BatchEmbedOutput {
        token_counts: vec![10, 20],
        success: true,
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = list_types_laic::BatchEmbedOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.token_counts, vec![10, 20]);
    assert!(decoded.success);
}

// ── map_types: map<K,V> roundtrip ──

#[test]
fn map_types_roundtrip() {
    let mut metadata = HashMap::new();
    metadata.insert("key1".to_string(), "val1".to_string());
    metadata.insert("key2".to_string(), "val2".to_string());

    let mut scores = HashMap::new();
    scores.insert("a".to_string(), 0.95);
    scores.insert("b".to_string(), 0.42);

    let mut flags = HashMap::new();
    flags.insert(1i32, true);
    flags.insert(2i32, false);

    let input = map_types_laic::MapDemoInput {
        metadata,
        scores,
        flags,
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = map_types_laic::MapDemoInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(
        decoded.metadata.get("key1").map(|s| s.as_str()),
        Some("val1")
    );
    assert_eq!(decoded.scores.get("a"), Some(&0.95));
    assert_eq!(decoded.flags.get(&1), Some(&true));

    let mut results = HashMap::new();
    results.insert("x".to_string(), 100i32);
    let mut labels = HashMap::new();
    labels.insert("x".to_string(), "label_x".to_string());

    let output = map_types_laic::MapDemoOutput { results, labels };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = map_types_laic::MapDemoOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.results.get("x"), Some(&100));
    assert_eq!(decoded.labels.get("x").map(|s| s.as_str()), Some("label_x"));
}

// ── optional_types: optional<T> roundtrip ──

#[test]
fn optional_types_with_values() {
    let input = optional_types_laic::SearchInput {
        query: "test query".into(),
        max_results: Some(10),
        filter_tag: Some("tag1".into()),
        threshold: Some(0.75),
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = optional_types_laic::SearchInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.query, "test query");
    assert_eq!(decoded.max_results, Some(10));
    assert_eq!(decoded.filter_tag.as_deref(), Some("tag1"));
    assert_eq!(decoded.threshold, Some(0.75));
}

#[test]
fn optional_types_with_none() {
    let input = optional_types_laic::SearchInput {
        query: "test".into(),
        max_results: None,
        filter_tag: None,
        threshold: None,
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = optional_types_laic::SearchInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.max_results, None);
    assert_eq!(decoded.filter_tag, None);
    assert_eq!(decoded.threshold, None);
}

#[test]
fn optional_output_roundtrip() {
    let output = optional_types_laic::SearchOutput {
        results: vec!["r1".into(), "r2".into()],
        total_count: 2,
        next_cursor: Some("cursor_abc".into()),
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = optional_types_laic::SearchOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.results, vec!["r1", "r2"]);
    assert_eq!(decoded.total_count, 2);
    assert_eq!(decoded.next_cursor.as_deref(), Some("cursor_abc"));
}

// ── image_classify: bytes + defaults + tensor[_,N] ──

#[test]
fn image_classify_roundtrip() {
    let input = image_classify_laic::ImageClassifyInput {
        image_data: vec![0xFF, 0xD8, 0xFF, 0xE0],
        top_k: 3,
        threshold: 0.8,
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded =
        image_classify_laic::ImageClassifyInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.image_data, vec![0xFF, 0xD8, 0xFF, 0xE0]);
    assert_eq!(decoded.top_k, 3);
    assert!((decoded.threshold - 0.8).abs() < f64::EPSILON);

    // tensor<f32>[_, 512]: dynamic first dim, 2 rows × 512 cols = 1024 floats → raw bytes
    let features_f32: Vec<f32> = (0..1024).map(|i| i as f32 * 0.01).collect();
    let features_bytes = f32_to_bytes(&features_f32);
    let output = image_classify_laic::ImageClassifyOutput {
        features: features_bytes.clone(),
        label: "cat".into(),
        confidence: 0.97,
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded =
        image_classify_laic::ImageClassifyOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.features.len(), 1024 * 4);
    assert_eq!(decoded.features, features_bytes);
    assert_eq!(decoded.label, "cat");
    assert!((decoded.confidence - 0.97).abs() < f64::EPSILON);
}

// ── tensor_container: list<tensor> + optional<tensor> ──

#[test]
fn tensor_container_roundtrip() {
    // list<tensor<f32>[768]> → Vec<Vec<u8>>
    let emb1_f32: Vec<f32> = (0..768).map(|i| i as f32).collect();
    let emb2_f32: Vec<f32> = (0..768).map(|i| (i as f32) * 2.0).collect();
    let emb1_bytes = f32_to_bytes(&emb1_f32);
    let emb2_bytes = f32_to_bytes(&emb2_f32);

    // tensor<f32>[3, 224, 224] → Vec<u8>
    let primary_f32: Vec<f32> = vec![0.5; 3 * 224 * 224];
    let primary_bytes = f32_to_bytes(&primary_f32);

    let input = tensor_container_laic::TensorContainerInput {
        embeddings: vec![emb1_bytes.clone(), emb2_bytes.clone()],
        primary: primary_bytes.clone(),
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded =
        tensor_container_laic::TensorContainerInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.embeddings.len(), 2);
    assert_eq!(decoded.embeddings[0].len(), 768 * 4);
    assert_eq!(decoded.embeddings[1].len(), 768 * 4);
    assert_eq!(decoded.primary.len(), 3 * 224 * 224 * 4);

    // optional<tensor<f64>[512]> → Option<Vec<u8>>
    let features_f64: Vec<f64> = (0..512).map(|i| i as f64 * 0.1).collect();
    let features_bytes = f64_to_bytes(&features_f64);

    // list<tensor<f32>[10]> → Vec<Vec<u8>>
    let score1_f32: Vec<f32> = vec![1.0; 10];
    let score2_f32: Vec<f32> = vec![2.0; 10];
    let score1_bytes = f32_to_bytes(&score1_f32);
    let score2_bytes = f32_to_bytes(&score2_f32);

    let output = tensor_container_laic::TensorContainerOutput {
        features: Some(features_bytes.clone()),
        scores: vec![score1_bytes.clone(), score2_bytes.clone()],
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded =
        tensor_container_laic::TensorContainerOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.features.as_ref().map(|v| v.len()), Some(512 * 8));
    assert_eq!(decoded.features, Some(features_bytes));
    assert_eq!(decoded.scores.len(), 2);
    assert_eq!(decoded.scores[0].len(), 10 * 4);
}

// ── errors_only: 4 error variants ──

#[test]
fn errors_only_roundtrip() {
    let input = errors_only_laic::HealthInput {
        service_name: "api-gateway".into(),
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = errors_only_laic::HealthInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.service_name, "api-gateway");
}

#[test]
fn errors_only_error_enum() {
    // skill name "health_check" → to_pascal_case → "HealthCheck" → "HealthCheckError"
    assert_eq!(
        errors_only_laic::HealthCheckError::ServiceUnavailable.code(),
        1
    );
    assert_eq!(errors_only_laic::HealthCheckError::Timeout.code(), 2);
    assert_eq!(errors_only_laic::HealthCheckError::InternalError.code(), 3);
    assert_eq!(
        errors_only_laic::HealthCheckError::DependencyFailed.code(),
        4
    );
    assert_eq!(
        errors_only_laic::HealthCheckError::Timeout.name(),
        "TIMEOUT"
    );
    assert!(errors_only_laic::HealthCheckError::from_code(5).is_none());
}

// ── multi_skill: 2 skills in one file ──

#[test]
fn multi_skill_tokenize_roundtrip() {
    let input = multi_skill_laic::TokenizeInput {
        text: "hello world".into(),
        max_length: 128,
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = multi_skill_laic::TokenizeInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.text, "hello world");
    assert_eq!(decoded.max_length, 128);

    // tensor<i32>[_] → Vec<u8>
    let token_ids_i32: Vec<i32> = vec![101, 7592, 2088, 102];
    let token_ids_bytes = i32_to_bytes(&token_ids_i32);
    let attention_mask_i32: Vec<i32> = vec![1, 1, 1, 1];
    let attention_mask_bytes = i32_to_bytes(&attention_mask_i32);

    let output = multi_skill_laic::TokenizeOutput {
        token_ids: token_ids_bytes.clone(),
        attention_mask: attention_mask_bytes.clone(),
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = multi_skill_laic::TokenizeOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.token_ids, token_ids_bytes);
    assert_eq!(decoded.attention_mask, attention_mask_bytes);
}

#[test]
fn multi_skill_detokenize_roundtrip() {
    // tensor<i32>[_] → Vec<u8>
    let token_ids_i32: Vec<i32> = vec![101, 7592, 2088, 102];
    let token_ids_bytes = i32_to_bytes(&token_ids_i32);

    let input = multi_skill_laic::DetokenizeInput {
        token_ids: token_ids_bytes.clone(),
    };
    let bytes = input.to_arrow_ipc().expect("serialize");
    let decoded = multi_skill_laic::DetokenizeInput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.token_ids, token_ids_bytes);

    let output = multi_skill_laic::DetokenizeOutput {
        text: "hello world".into(),
    };
    let bytes = output.to_arrow_ipc().expect("serialize");
    let decoded = multi_skill_laic::DetokenizeOutput::from_arrow_ipc(&bytes).expect("deserialize");
    assert_eq!(decoded.text, "hello world");
}

#[test]
fn multi_skill_metadata() {
    assert_eq!(multi_skill_laic::TokenizeInput::skill_id(), "tokenize");
    assert_eq!(multi_skill_laic::TokenizeInput::version(), "2.0.0");
    assert_eq!(multi_skill_laic::DetokenizeInput::skill_id(), "detokenize");
    assert_eq!(multi_skill_laic::DetokenizeOutput::direction(), "output");
}
