//! Verification crate — ensures laicc-generated code compiles and roundtrips.
//!
//! This crate has no runtime code. All verification happens in `tests/roundtrip.rs`
//! against code generated by `build.rs`.
